### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIydUdxVjgrZWUrSWcwb1Nmc0NmZjIwOExpNzlDMUlma3dNU2grcThldmR3PSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzI1NjcwMTY3LCJleHAiOjE3MjU3NTY1Njd9.cHEijZ-m6M8BBExG7k4C3zRfFAotH20fAw0smQ27yE4

{
  "name": "나이키 에어포스",
  "description": "상품 설명",
  "items": [
    {
      "name": "270",
      "price": 100000,
      "count": 1
    }
  ]
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIydUdxVjgrZWUrSWcwb1Nmc0NmZjIwOExpNzlDMUlma3dNU2grcThldmR3PSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzI1NjcwMTY3LCJleHAiOjE3MjU3NTY1Njd9.cHEijZ-m6M8BBExG7k4C3zRfFAotH20fAw0smQ27yE4

{
  "productId": 1,
  "name": "280",
  "price": 100000,
  "count": 1
}
